[tool.poetry]
name = "gswarm-profiler"
version = "0.1.0"
description = "Multi-node multi-GPU profiler"
authors = ["Chivier Humber <chivier.humber@outlook.com>"]
packages = [
    { include = "gswarm_profiler" }
]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.0"}
typer = {extras = ["all"], version = "^0.9.0"}
nvitop = ">=1.3.0" # Ensure version with PCIe throughput
websockets = "^11.0.3" # For the client
loguru = "^0.7.0" # For better logging
aiofiles = "^23.1.0" # For async file writes
requests = "^2.32.3"

[tool.poetry.scripts]
gswarm-profiler = "gswarm_profiler.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
