#!/bin/bash
# Manual test script for SGLang PD separation

echo "======================================================================="
echo "MANUAL SGLANG PD-SEPARATION TEST"
echo "======================================================================="
echo ""
echo "This script shows how to manually set up PD-separated inference."
echo ""
echo "Step 1: Launch prefill server (in terminal 1):"
echo "-----------------------------------------------------------------------"
echo "export CUDA_VISIBLE_DEVICES=1"
echo "export CUDA_HOME=/usr/local/cuda-12.6"
echo "export LD_LIBRARY_PATH=/usr/local/cuda-12.6/targets/x86_64-linux/lib:\$LD_LIBRARY_PATH"
echo ""
echo "python -m sglang.launch_server \\"
echo "  --model-path microsoft/phi-2 \\"
echo "  --port 30000 \\"
echo "  --mem-fraction-static 0.5 \\"
echo "  --disable-cuda-graph \\"
echo "  --attention-backend triton \\"
echo "  --chunked-prefill-size 4096"
echo ""
echo "Step 2: Launch decode server (in terminal 2):"
echo "-----------------------------------------------------------------------"
echo "export CUDA_VISIBLE_DEVICES=2"
echo "export CUDA_HOME=/usr/local/cuda-12.6"
echo "export LD_LIBRARY_PATH=/usr/local/cuda-12.6/targets/x86_64-linux/lib:\$LD_LIBRARY_PATH"
echo ""
echo "python -m sglang.launch_server \\"
echo "  --model-path microsoft/phi-2 \\"
echo "  --port 30001 \\"
echo "  --mem-fraction-static 0.5 \\"
echo "  --disable-cuda-graph \\"
echo "  --attention-backend triton \\"
echo "  --max-running-requests 16"
echo ""
echo "Step 3: Test prefill (in terminal 3):"
echo "-----------------------------------------------------------------------"
echo "curl -X POST http://localhost:30000/generate \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"text\": \"What is artificial intelligence?\","
echo "    \"sampling_params\": {"
echo "      \"max_new_tokens\": 1,"
echo "      \"temperature\": 0.0"
echo "    }"
echo "  }'"
echo ""
echo "Step 4: Test decode (continue from prefill output):"
echo "-----------------------------------------------------------------------"
echo "# Use the output from step 3 as input"
echo "curl -X POST http://localhost:30001/generate \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"text\": \"What is artificial intelligence? <first_token_here>\","
echo "    \"sampling_params\": {"
echo "      \"max_new_tokens\": 50,"
echo "      \"temperature\": 0.7"
echo "    }"
echo "  }'"
echo ""
echo "======================================================================="
echo "KEY POINTS:"
echo "======================================================================="
echo "1. Phi-2 requires --disable-cuda-graph due to head_dim=80"
echo "2. Use --attention-backend triton to avoid FlashInfer issues"
echo "3. First request may take 30-60 seconds to initialize"
echo "4. In production, KV cache would be transferred between servers"
echo ""
echo "For automated testing, see the Python demo scripts."
echo "======================================================================="