models:
  llm7b:
    name: LLM-7B
    memory_gb: 14
    gpus_required: 1
    load_time_seconds: 10
    tokens_per_second: 50
    token_mean: 512
    token_std: 128
  llm30b:
    name: LLM-30B
    memory_gb: 60
    gpus_required: 4
    load_time_seconds: 40
    tokens_per_second: 20
    token_mean: 1024
    token_std: 256
  stable_diffusion:
    name: Stable-Diffusion
    memory_gb: 8
    gpus_required: 1
    load_time_seconds: 6
    inference_time_mean: 2.0
    inference_time_std: 0.5
    config:
      width:
      - 512
      - 768
      - 1024
      height:
      - 512
      - 768
      - 1024
workflows:
  workflow1:
    name: LLM to Image Generation
    nodes:
    - id: node1
      model: llm7b
      inputs:
      - user_prompt
      outputs:
      - image_prompt
    - id: node2
      model: stable_diffusion
      inputs:
      - image_prompt
      outputs:
      - generated_image
      config_options:
      - width
      - height
    edges:
    - from: node1
      to: node2
  workflow2:
    name: LLM Fork and Merge
    nodes:
    - id: node1
      model: llm7b
      inputs:
      - user_prompt
      outputs:
      - initial_analysis
    - id: node2
      model: llm30b
      inputs:
      - initial_analysis
      outputs:
      - deep_analysis_1
    - id: node3
      model: llm30b
      inputs:
      - initial_analysis
      outputs:
      - deep_analysis_2
    - id: node4
      model: llm7b
      inputs:
      - deep_analysis_1
      - deep_analysis_2
      outputs:
      - final_summary
    edges:
    - from: node1
      to: node2
    - from: node1
      to: node3
    - from: node2
      to: node4
    - from: node3
      to: node4
